### ISSUE TITLE
Добавление одинаковых подграфов в разные места координатора

### ISSUE THREAD

**Issue by kocherovets** [nikans/MonarchRouter#13]
Добрый день!

А каким образом предполагается строить роутинг для, например, случая выбора адреса, когда он реализуется с помощью довольно сложного интерфейса из скажем 3 вьюконтроллеров добавляющихся через навбарвьюконтроллер? И когда нужно прикрутить этот выбор в 3 разных местах программы.

**Comment by nikans** [comment]
@kocherovets 
1. Не уверен, что это имеет смысл показывать роутером, когда выбор подкомпонентов адреса осуществляется на вьюконтроллерах, вызывающихся из одного "главного" VC для формирования адреса целиком. Может быть, имеет смысл роутить только на этот главный VC?
Если все же использовать роутер, то это выглядит как случай, где в `stack`-node (navigation controller) добавлен один `endpoint`-node (формирование адреса), у которого есть `children[]` в виде нескольких других `endpoint` (формирование компонентов адреса). 

2. Monarch используется для навигации из любого места приложения в любое, соответственно, все пути должны быть однозначно определены. Поэтому, нужно будет задать уникальные `Route` (это могут быть [просто строки](https://github.com/nikans/MonarchRouter#1-define-your-apps-routes)) для каждого узла графа. Вызывать переход на них нужно соответствующим образом сформированным `RoutingRequest` (это могут быть [просто URL](https://github.com/nikans/MonarchRouter#11-optionally-define-a-set-of-routingrequests)). 

Соответственно, `Route`s могут выглядеть, например, так:
- order/address
- order/address/country
- order/address/city
- order/address/street
- user/address
- user/address/country
- user/address/city
- user/address/street

В координаторе нужно будет добавить по одному узлу на каждый `Route`, но при этом можно переиспользовать презентеры, формирующие вьюкотроллеры, которых для данного случая будет 4: для формирования адреса, для выбора страны, города, улицы.

**Comment by kocherovets** [comment]
А что если добавить функциональность поддержки неуникальных Route и осуществлять переход с учетом расстояния до целевого маршрута от текущего? Это что-то ломает в текущей архитектуре? По идее такие переходы не будут инициироваться без учета контекста и поэтому все должно быть ок.

**Comment by nikans** [comment]
Можно попробовать. 

Но это стоит делать вместе с переходом на function builder'ы для построения иерархии координатора. В описанном кейсе я не вижу смысла заморачиваться — в три места добавить узлы не страшно. Преимущество тут будет скорее в случае рекурсивных роутов.

**Comment by kocherovets** [comment]
А что за function builder'ы? Они где-то описаны?
