### ISSUE TITLE
Could Monarch be used without Storyboard?

### ISSUE THREAD

**Issue by netgfx** [nikans/MonarchRouter#5]
Is there an example with code only approach? Or what should change on the provided example to work only with code and no storyboard?

**Comment by nikans** [comment]
Hello @netgfx. Sorry for late reply. 
Sure it can be used without storyboards — the router basically doesn't care how do you instantiate your VSc. Simply swap VC instantiation with your own preferred method.

**Comment by netgfx** [comment]
Great thank you!
